CREATE TABLE IF NOT EXISTS items (
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `imageURL` VARCHAR(255) NOT NULL,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,

  PRIMARY KEY (id)
);

