CREATE TABLE IF NOT EXISTS users (
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,

  PRIMARY KEY (id),
  UNIQUE KEY (email)
);
